name: Manually Build Release Zip

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        type: string
      zip:
        description: 'Output zip filename (e.g. my-plugin.zip)'
        required: true
        type: string

jobs:
  create-release:
    name: Create Release Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build plugin
        run: |
          if ! composer install --no-dev; then
            echo "::error::Plugin build failed"
            exit 1
          fi

      - name: Create zip archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: ${{ github.event.inputs.zip }}
          exclusions: '*.git* .editorconfig composer* *.md'

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        id: upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ github.event.inputs.zip }}
          tag_name: ${{ github.event.inputs.tag }}
          fail_on_unmatched_files: true

      - name: Output upload URL
        run: |
          echo ${{ steps.upload.outputs.upload_url }}

      - name: Generate build provenance attestation
        uses: johnbillion/action-wordpress-plugin-attestation@0.7.0
        with:
          zip-url: ${{ steps.upload.outputs.html_url }}
      - name: Cleanup
        if: always()
        run: rm -f ${{ github.event.inputs.zip }}
